<a href="https://colab.research.google.com/github/rashi789/rashi/blob/basicpython/crypto_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 pip install urllib3

In [ ]:
import urllib.request

response = urllib.request.urlopen( "http://example.com/" )
print(response.status)


200


In [ ]:
from urllib.request import Request, urlopen

req = Request(
    url='https://reqres.in/api/users?page=2',
    headers={'User-Agent': 'Mozilla/5.0'}
)
webpage = urlopen(req).read()
print(webpage)

b'{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free, contributions towards 

In [ ]:
import requests

response = requests.get( 'https://reqres.in/api/users?page=2')
print(response.text)

{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free, contributions towards se

In [ ]:
import requests

# The API endpoint
url = "https://jsonplaceholder.typicode.com/posts/1"

# A GET request to the API
response = requests.get(url)

# Print the response
response_json = response.json()
print(response_json)

"""
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
"""

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}


"\n{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}\n"

In [ ]:
import requests
import json
response = requests.get('https://reqres.in/api/users?page=2')
print('HTTP response content:',response.content)
y = json.loads(response.content)
print(y["data"][0]["email"])

HTTP response content: b'{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free,

In [ ]:
import requests
import json
response = requests.get('https://reqres.in/api/users?page=2')
print('HTTP response content:',response.content)
y = json.loads(response.content)
for row in y["data"]:
  print(row["email"])
#print(y["data"[0]["email"])
#print(y["data"][0]["id"])

HTTP response content: b'{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free,

In [1]:
import numpy as np
import sklearn as sk
home=[1000,2000,3000,4000,5000,6000,7000,8000,9000,10000]
price=[100,200,300,400,500,600,700,800,900,1000]
arr=np.array(home)
arr2=np.array(price)
print(arr)
print(arr2)
print(type(arr))

[ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]
[ 100  200  300  400  500  600  700  800  900 1000]
<class 'numpy.ndarray'>


In [36]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
home = np.array([1000,2000,3000,4000,5000,6000,7000,8000,9000,10000])
price = np.array([100,200,300,400,500,600,700,800,900,1000])
print(home)
print(price)

home_train, home_test, price_train, price_test = train_test_split(
    home,price,random_state=41,test_size=0.5,shuffle=True)
print("home_train:",home_train)
print("home_test:",home_test)
print("price_train:",price_train)
print("price_test:",price_test)

[ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]
[ 100  200  300  400  500  600  700  800  900 1000]
home_train: [10000  3000  5000  4000  1000]
home_test: [6000 7000 8000 9000 2000]
price_train: [1000  300  500  400  100]
price_test: [600 700 800 900 200]


In [64]:
import numpy as np

import sklearn as sk

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
home = np.array([100, 200, 300, 400, 500])

price = np.array([1500, 2500, 3500,4500, 5500])

print(home)

print(price)

home_train, home_test, price_train, price_test train_test_split( home, price, random_state=41, test_size=0.5,shuffle-True)

print("home_train:",home_train)

print("home_test:", home_test)

print("price_train:",price_train)

print("price_test:",price_test)

home_train=home_train.reshape(-1,1)

home_test=home_test.reshape(-1,1)

price_train=price_train.reshape(-1,1)

price_test=price_test.reshape(-1,1)

regr.LinearRegression()

regr.fit(home_train, price_train)

print(regr.score(home_test,price_test))

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (<ipython-input-64-b74f056c41a8>, line 16)